### ISSUE TITLE
Browser tests fail

### ISSUE THREAD

**Issue by colinsullivan** [parshap/js-opc#4]
Heyo,

`Buffer` class is used in `test.js` which is not available in Browsers:

```
Uncaught TypeError: Buffer.alloc is not a function
    at getBuffer (test-bundle.js:11774)
    at module.exports (test-bundle.js:11774)
    at Test.<anonymous> (test-bundle.js:11788)
    at Test.bound [as _cb] (test-bundle.js:8090)
    at Test.run (test-bundle.js:8103)
    at Test.bound [as run] (test-bundle.js:8090)
    at next (test-bundle.js:7900)
    at test-bundle.js:5322
    at Array.forEach (<anonymous>)
    at MutationObserver.<anonymous> (test-bundle.js:5321)
```

**Comment by colinsullivan** [comment]
Related, `Buffer.alloc` isn't in `iojs`, so those tests are failing on travis:

https://travis-ci.org/colinsullivan/js-opc/jobs/375627474

```
/home/travis/build/colinsullivan/js-opc/strand.js:21
    return Buffer.alloc(input * 3);
                  ^
TypeError: Buffer.alloc is not a function
    at getBuffer (/home/travis/build/colinsullivan/js-opc/strand.js:21:19)
    at module.exports (/home/travis/build/colinsullivan/js-opc/strand.js:51:16)
    at Test.<anonymous> (/home/travis/build/colinsullivan/js-opc/test.js:10:16)
    at Test.bound [as _cb] (/home/travis/build/colinsullivan/js-opc/node_modules/tape/lib/test.js:62:32)
    at Test.run (/home/travis/build/colinsullivan/js-opc/node_modules/tape/lib/test.js:75:10)
    at Test.bound [as run] (/home/travis/build/colinsullivan/js-opc/node_modules/tape/lib/test.js:62:32)
    at Immediate.next [as _onImmediate] (/home/travis/build/colinsullivan/js-opc/node_modules/tape/lib/results.js:66:15)
    at processImmediate [as _immediateCallback] (timers.js:371:17)
```
